runtime: php74

runtime_config:
 document_root: public

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:RVUb0zGuXv/d0XNydDVdxYLiSRQLojZmw9P8uONNSC4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie


handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
